"""MVP ResumeStorage backend — local filesystem, selected by
RESUME_STORAGE_BACKEND=local (the only backend for now; see base.py).

Security note: storage_key is always server-generated by ResumeService
(app/services/resume/resume_service.py) as f"{user_id}/{uuid4().hex}.pdf"
— never derived from a client-supplied filename. `_resolve` still
defends in depth against path traversal (rejecting any key that would
resolve outside the configured base directory) so a bug elsewhere in the
call chain can't turn into an arbitrary-file write/read.
"""

import asyncio
from pathlib import Path

from app.core.config import Settings
from app.storage.base import ResumeStorage


class PathTraversalError(ValueError):
    pass


class LocalResumeStorage(ResumeStorage):
    def __init__(self, settings: Settings) -> None:
        self._base_dir = Path(settings.RESUME_STORAGE_LOCAL_DIR).resolve()
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def _resolve(self, storage_key: str) -> Path:
        candidate = (self._base_dir / storage_key).resolve()
        if self._base_dir not in candidate.parents and candidate != self._base_dir:
            raise PathTraversalError(
                f"storage_key resolves outside the storage root: {storage_key!r}"
            )
        return candidate

    async def save(self, *, storage_key: str, content: bytes) -> str:
        path = self._resolve(storage_key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)

        await asyncio.to_thread(_write)
        return storage_key

    async def read(self, *, storage_key: str) -> bytes:
        path = self._resolve(storage_key)

        def _read() -> bytes:
            if not path.is_file():
                raise FileNotFoundError(storage_key)
            return path.read_bytes()

        return await asyncio.to_thread(_read)

    async def delete(self, *, storage_key: str) -> None:
        path = self._resolve(storage_key)

        def _delete() -> None:
            path.unlink(missing_ok=True)

        await asyncio.to_thread(_delete)
