"""initial schema

Revision ID: 4673e588c6c7
Revises: 
Create Date: 2026-07-28 07:59:53.802842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4673e588c6c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('interview_style_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.Enum('local', 'google', name='users_auth_provider_enum'), nullable=False),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('candidate', 'recruiter', 'admin', name='users_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('parsed_status', sa.Enum('pending', 'processing', 'done', 'failed', name='resumes_parsed_status_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('intern', 'junior', 'mid', 'senior', 'staff', name='roles_level_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('proficiency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trend', sa.Enum('improving', 'stable', 'declining', name='skill_progress_trend_enum'), nullable=False),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name')
    )
    op.create_index(op.f('ix_skill_progress_user_id'), 'skill_progress', ['user_id'], unique=False)
    op.create_table('user_progress_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('interviews_completed', sa.Integer(), nullable=False),
    sa.Column('avg_overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date')
    )
    op.create_index(op.f('ix_user_progress_snapshots_user_id'), 'user_progress_snapshots', ['user_id'], unique=False)
    op.create_table('interview_templates',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_difficulty', sa.Enum('easy', 'medium', 'hard', name='interview_templates_default_difficulty_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_experience',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experience_resume_id'), 'resume_experience', ['resume_id'], unique=False)
    op.create_table('resume_gap_analysis',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_difficulty', sa.Enum('easy', 'medium', 'hard', name='resume_gap_analysis_recommended_difficulty_enum'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_gap_analysis_resume_id'), 'resume_gap_analysis', ['resume_id'], unique=False)
    op.create_table('resume_projects',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_projects_resume_id'), 'resume_projects', ['resume_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('proficiency_hint', sa.Enum('beginner', 'intermediate', 'advanced', name='resume_skills_proficiency_hint_enum'), nullable=True),
    sa.Column('source', sa.Enum('explicit', 'inferred', name='resume_skills_source_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_skills_resume_id'), 'resume_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_skills_skill_name'), 'resume_skills', ['skill_name'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'abandoned', name='interview_sessions_status_enum'), nullable=False),
    sa.Column('current_round_sequence', sa.Integer(), nullable=False),
    sa.Column('current_difficulty', sa.Enum('easy', 'medium', 'hard', name='interview_sessions_current_difficulty_enum'), nullable=False),
    sa.Column('langgraph_thread_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('langgraph_thread_id')
    )
    op.create_index('ix_interview_sessions_user_status', 'interview_sessions', ['user_id', 'status'], unique=False)
    op.create_table('template_rounds',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.Enum('introduction', 'technical', 'coding', 'behavioral', 'system_design', 'resume_discussion', 'final', name='template_rounds_round_type_enum'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('difficulty_override', sa.Enum('easy', 'medium', 'hard', name='template_rounds_difficulty_override_enum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'sequence_no')
    )
    op.create_index(op.f('ix_template_rounds_template_id'), 'template_rounds', ['template_id'], unique=False)
    op.create_table('company_readiness',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('readiness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_interview_session_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_interview_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id')
    )
    op.create_index(op.f('ix_company_readiness_user_id'), 'company_readiness', ['user_id'], unique=False)
    op.create_table('interview_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_explanation', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('interview_rounds',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('template_round_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.Enum('introduction', 'technical', 'coding', 'behavioral', 'system_design', 'resume_discussion', 'final', name='interview_rounds_round_type_enum'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('planned_difficulty', sa.Enum('easy', 'medium', 'hard', name='interview_rounds_planned_difficulty_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'skipped', name='interview_rounds_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_round_id'], ['template_rounds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_no')
    )
    op.create_index(op.f('ix_interview_rounds_session_id'), 'interview_rounds', ['session_id'], unique=False)
    op.create_table('learning_roadmaps',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['interview_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('questions',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='questions_difficulty_enum'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'open', 'coding', 'system_design', name='questions_question_type_enum'), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('bank', 'generated', name='questions_source_enum'), nullable=False),
    sa.Column('vector_ref', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_round_id'), 'questions', ['round_id'], unique=False)
    op.create_table('report_section_scores',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.Enum('technical', 'coding', 'communication', 'problem_solving', 'confidence', name='report_section_scores_section_enum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['interview_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'section')
    )
    op.create_index(op.f('ix_report_section_scores_report_id'), 'report_section_scores', ['report_id'], unique=False)
    op.create_table('report_strong_areas',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['interview_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_strong_areas_report_id'), 'report_strong_areas', ['report_id'], unique=False)
    op.create_table('report_weak_areas',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='report_weak_areas_severity_enum'), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['interview_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_weak_areas_report_id'), 'report_weak_areas', ['report_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_test_cases',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'sequence_no')
    )
    op.create_index(op.f('ix_question_test_cases_question_id'), 'question_test_cases', ['question_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('resource_title', sa.Text(), nullable=False),
    sa.Column('resource_url', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.Enum('article', 'video', 'course', 'practice', name='roadmap_items_resource_type_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['learning_roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_items_roadmap_id'), 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_table('answer_evaluations',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_explanation', sa.Text(), nullable=False),
    sa.Column('problem_solving_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('problem_solving_explanation', sa.Text(), nullable=False),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_explanation', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confidence_explanation', sa.Text(), nullable=False),
    sa.Column('difficulty_signal', sa.Enum('increase', 'decrease', 'maintain', name='answer_evaluations_difficulty_signal_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_table('code_submissions',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('execution_status', sa.Enum('queued', 'running', 'success', 'partial', 'error', 'timeout', name='code_submissions_execution_status_enum'), nullable=False),
    sa.Column('executor', sa.Text(), nullable=True),
    sa.Column('passed_test_count', sa.Integer(), nullable=True),
    sa.Column('total_test_count', sa.Integer(), nullable=True),
    sa.Column('total_runtime_ms', sa.Integer(), nullable=True),
    sa.Column('peak_memory_kb', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'attempt_no')
    )
    op.create_index(op.f('ix_code_submissions_answer_id'), 'code_submissions', ['answer_id'], unique=False)
    op.create_index('ux_code_submissions_final', 'code_submissions', ['answer_id'], unique=True, postgresql_where=sa.text('is_final'))
    op.create_table('code_submission_test_results',
    sa.Column('code_submission_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['code_submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['question_test_cases.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_submission_id', 'test_case_id')
    )
    op.create_index(op.f('ix_code_submission_test_results_code_submission_id'), 'code_submission_test_results', ['code_submission_id'], unique=False)
    op.create_table('coding_evaluations',
    sa.Column('code_submission_id', sa.UUID(), nullable=False),
    sa.Column('correctness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('correctness_explanation', sa.Text(), nullable=False),
    sa.Column('time_complexity', sa.Text(), nullable=True),
    sa.Column('space_complexity', sa.Text(), nullable=True),
    sa.Column('readability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('readability_explanation', sa.Text(), nullable=False),
    sa.Column('optimization_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('optimization_explanation', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_submission_id'], ['code_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_evaluations')
    op.drop_index(op.f('ix_code_submission_test_results_code_submission_id'), table_name='code_submission_test_results')
    op.drop_table('code_submission_test_results')
    op.drop_index('ux_code_submissions_final', table_name='code_submissions', postgresql_where=sa.text('is_final'))
    op.drop_index(op.f('ix_code_submissions_answer_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_table('answer_evaluations')
    op.drop_index(op.f('ix_roadmap_items_roadmap_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_question_test_cases_question_id'), table_name='question_test_cases')
    op.drop_table('question_test_cases')
    op.drop_table('answers')
    op.drop_index(op.f('ix_report_weak_areas_report_id'), table_name='report_weak_areas')
    op.drop_table('report_weak_areas')
    op.drop_index(op.f('ix_report_strong_areas_report_id'), table_name='report_strong_areas')
    op.drop_table('report_strong_areas')
    op.drop_index(op.f('ix_report_section_scores_report_id'), table_name='report_section_scores')
    op.drop_table('report_section_scores')
    op.drop_index(op.f('ix_questions_round_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('learning_roadmaps')
    op.drop_index(op.f('ix_interview_rounds_session_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    op.drop_table('interview_reports')
    op.drop_index(op.f('ix_company_readiness_user_id'), table_name='company_readiness')
    op.drop_table('company_readiness')
    op.drop_index(op.f('ix_template_rounds_template_id'), table_name='template_rounds')
    op.drop_table('template_rounds')
    op.drop_index('ix_interview_sessions_user_status', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_resume_skills_skill_name'), table_name='resume_skills')
    op.drop_index(op.f('ix_resume_skills_resume_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_projects_resume_id'), table_name='resume_projects')
    op.drop_table('resume_projects')
    op.drop_index(op.f('ix_resume_gap_analysis_resume_id'), table_name='resume_gap_analysis')
    op.drop_table('resume_gap_analysis')
    op.drop_index(op.f('ix_resume_experience_resume_id'), table_name='resume_experience')
    op.drop_table('resume_experience')
    op.drop_table('interview_templates')
    op.drop_index(op.f('ix_user_progress_snapshots_user_id'), table_name='user_progress_snapshots')
    op.drop_table('user_progress_snapshots')
    op.drop_index(op.f('ix_skill_progress_user_id'), table_name='skill_progress')
    op.drop_table('skill_progress')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Alembic's autogenerate doesn't emit DROP TYPE for native Postgres
    # enums on downgrade (op.drop_table() has no column/type awareness) —
    # left alone, a downgrade-then-upgrade cycle fails with
    # "type already exists". Every enum from app/models/enums.py, dropped
    # explicitly once its last referencing table is gone above.
    for enum_name in (
        "answer_evaluations_difficulty_signal_enum",
        "code_submissions_execution_status_enum",
        "interview_rounds_planned_difficulty_enum",
        "interview_rounds_round_type_enum",
        "interview_rounds_status_enum",
        "interview_sessions_current_difficulty_enum",
        "interview_sessions_status_enum",
        "interview_templates_default_difficulty_enum",
        "questions_difficulty_enum",
        "questions_question_type_enum",
        "questions_source_enum",
        "report_section_scores_section_enum",
        "report_weak_areas_severity_enum",
        "resume_gap_analysis_recommended_difficulty_enum",
        "resume_skills_proficiency_hint_enum",
        "resume_skills_source_enum",
        "resumes_parsed_status_enum",
        "roadmap_items_resource_type_enum",
        "roles_level_enum",
        "skill_progress_trend_enum",
        "template_rounds_difficulty_override_enum",
        "template_rounds_round_type_enum",
        "users_auth_provider_enum",
        "users_role_enum",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
