"""resume intelligence

Revision ID: cadc0c718f96
Revises: e79590a1d210
Create Date: 2026-08-05 16:04:54.956153

Module 3 — additive only. No column on any pre-existing table is dropped,
renamed, or narrowed; every NOT NULL column added to a pre-existing table
carries a server_default so this applies cleanly even if resume rows
already exist. Auto-generated, then hand-adjusted:
  - server_default on every new NOT NULL column (booleans/JSONB)
  - the resume_gap_analysis.resume_id unique constraint given an explicit
    name instead of autogenerate's anonymous `None`
  - resume_skills_category_enum explicitly CREATEd before the add_column
    that references it (add_column, unlike create_table, doesn't do this
    implicitly) and DROPped on downgrade, matching the pattern in
    4673e588c6c7_initial_schema.py
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cadc0c718f96'
down_revision: Union[str, None] = 'e79590a1d210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_achievements',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_achievements_resume_id'), 'resume_achievements', ['resume_id'], unique=False)
    op.create_table('resume_certifications',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_certifications_resume_id'), 'resume_certifications', ['resume_id'], unique=False)
    op.create_table('resume_education',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('degree', sa.Text(), nullable=True),
    sa.Column('field_of_study', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_education_resume_id'), 'resume_education', ['resume_id'], unique=False)
    op.add_column('resume_experience', sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_experience', sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_experience', sa.Column('evidence_text', sa.Text(), nullable=True))
    op.add_column('resume_gap_analysis', sa.Column('role_key', sa.Text(), nullable=True))
    op.add_column('resume_gap_analysis', sa.Column('matching_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_gap_analysis', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_gap_analysis', sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_gap_analysis', sa.Column('difficulty_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_gap_analysis', sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('resume_gap_analysis', sa.Column('explanation', sa.Text(), nullable=True))
    op.drop_index('ix_resume_gap_analysis_resume_id', table_name='resume_gap_analysis')
    op.create_unique_constraint('uq_resume_gap_analysis_resume_id', 'resume_gap_analysis', ['resume_id'])
    op.add_column('resume_projects', sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_projects', sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('resume_projects', sa.Column('evidence_text', sa.Text(), nullable=True))
    # add_column (unlike create_table) does not implicitly CREATE TYPE for
    # a native Postgres enum referenced by the new column — create it
    # explicitly first (checkfirst=True makes this safe to re-run).
    resume_skills_category_enum = postgresql.ENUM(
        'programming_language', 'framework', 'database', 'cloud', 'ai_ml', 'developer_tool', 'other',
        name='resume_skills_category_enum',
    )
    resume_skills_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('resume_skills', sa.Column('category', resume_skills_category_enum, nullable=True))
    op.add_column('resume_skills', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('resume_skills', sa.Column('evidence_text', sa.Text(), nullable=True))
    op.add_column('resume_skills', sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('resumes', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('mime_type', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('content_sha256', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('detected_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('resumes', sa.Column('candidate_name', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('professional_summary', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('embeddings_indexed_at', sa.DateTime(timezone=True), nullable=True))
    # Partial unique index: at most one active resume per user. Historical
    # (is_active=false) resumes are unconstrained here — versioning
    # (module §10) requires many of those to coexist per user.
    op.create_index('uq_resumes_one_active_per_user', 'resumes', ['user_id'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_resumes_one_active_per_user', table_name='resumes', postgresql_where=sa.text('is_active'))
    op.drop_column('resumes', 'embeddings_indexed_at')
    op.drop_column('resumes', 'professional_summary')
    op.drop_column('resumes', 'candidate_name')
    op.drop_column('resumes', 'detected_sections')
    op.drop_column('resumes', 'content_sha256')
    op.drop_column('resumes', 'file_size_bytes')
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'processing_error')
    op.drop_column('resumes', 'is_active')
    op.drop_column('resume_skills', 'confidence')
    op.drop_column('resume_skills', 'evidence_text')
    op.drop_column('resume_skills', 'raw_text')
    op.drop_column('resume_skills', 'category')
    op.drop_column('resume_projects', 'evidence_text')
    op.drop_column('resume_projects', 'outcomes')
    op.drop_column('resume_projects', 'responsibilities')
    op.drop_constraint('uq_resume_gap_analysis_resume_id', 'resume_gap_analysis', type_='unique')
    op.create_index('ix_resume_gap_analysis_resume_id', 'resume_gap_analysis', ['resume_id'], unique=False)
    op.drop_column('resume_gap_analysis', 'explanation')
    op.drop_column('resume_gap_analysis', 'confidence')
    op.drop_column('resume_gap_analysis', 'difficulty_reasons')
    op.drop_column('resume_gap_analysis', 'focus_areas')
    op.drop_column('resume_gap_analysis', 'strengths')
    op.drop_column('resume_gap_analysis', 'matching_skills')
    op.drop_column('resume_gap_analysis', 'role_key')
    op.drop_column('resume_experience', 'evidence_text')
    op.drop_column('resume_experience', 'responsibilities')
    op.drop_column('resume_experience', 'technologies')
    op.drop_index(op.f('ix_resume_education_resume_id'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resume_certifications_resume_id'), table_name='resume_certifications')
    op.drop_table('resume_certifications')
    op.drop_index(op.f('ix_resume_achievements_resume_id'), table_name='resume_achievements')
    op.drop_table('resume_achievements')
    # ### end Alembic commands ###

    # Alembic's autogenerate doesn't emit DROP TYPE for native Postgres
    # enums (see 4673e588c6c7_initial_schema.py for the same pattern) —
    # dropped explicitly now that resume_skills.category (its last
    # reference) is gone above.
    op.execute("DROP TYPE resume_skills_category_enum")
